# Generated by Django 6.0.5 on 2026-07-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последний вход'),
        ),
    ]
