# Generated by Django 6.0.5 on 2026-07-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_last_seen_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Новое сообщение'), ('mention', 'Упоминание'), ('group_add', 'Добавлен в группу')], max_length=20),
        ),
    ]
