"""
Django settings for Constanta project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# TODO: Переехать на UV

# TODO: models.py -> models/
# TODO: utils.py -> utils/
# TODO: Использовать админку Django
# TODO: CSS и JS нужно хранить в static/css / static/js
# TODO: Выносить повторы CSS и JS в static/css/lib и static/js/lib
# TODO: Выносить повторы HTML-блоков в templates/parts


# TODO: Прибраться в настройках

from pathlib import Path
from environs import Env  # ← НОВОЕ: для работы с .env

# Инициализация environs
env = Env()
env.read_env()  # Читает файл .env из корня проекта

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    '127.0.0.1',
    '1.1.1.71',
    'http://1.1.1.71',
    '192.168.1.67',
    'http://192.168.1.67'
])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://1.1.1.71',
    'http://192.168.1.67'
])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat.apps.ChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middleware.IPBanMiddleware',
]

ROOT_URLCONF = 'Constanta.urls'

TEMPLATES = [
    # TODO: Посмотреть на возможность интеграции Jinja2
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # TODO: Использовать глобальные templates/, по необходимости делить на области видимости соответственно приложениям
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Constanta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # TODO: Не забывать про возможность внедрения более серьёзных БД ( MySQL / PostgresSQL )
    'default': env.dj_db_url('DATABASE_URL', default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# TODO: Логи, просто существуют - они важны, logs/, используй "конкурентный ротационный писарь"
# TODO: Используй разделение логов по модулям, ошибки и статика тоже отдельно

# 🔹 Базовая настройка логирования (можно расширить позже)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # TODO: Добавить RotatingFileHandler для продакшена
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE', default='ru')

# TODO: Переводить для клиентов в их локальное время ( н-р, moment.js )
TIME_ZONE = env('TIMEZONE', default='Asia/Vladivostok')  # ← Твой часовой пояс

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# TODO: Внедрить compress
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_DIRS = [BASE_DIR / 'Constanta' / 'static']

AUTH_USER_MODEL = 'chat.User'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# TODO: Не забывать про nginx
# 🔹 Максимальный размер файла (10 МБ)
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE', default=10 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DATA_UPLOAD_MAX_MEMORY_SIZE', default=10 * 1024 * 1024)


# Для дефолтной аватарки
STATICFILES_DIRS = [BASE_DIR / 'static']


LOGIN_URL = '/auth/'  # ← Наш кастомный URL входа
LOGIN_REDIRECT_URL = '/main/'  # Куда перенаправлять после входа
LOGOUT_REDIRECT_URL = '/auth/'  # Куда после выхода

# TODO: Это выглядит как костыль, у Django итак есть система авторизации из коробки
# TODO: is_muted ( ну типо мягкий бан ) и is_active ( полный бан )
AUTHENTICATION_BACKENDS = [
    'chat.backends.CustomAuthBackend',  # ← Наш кастомный (первым!)
    'django.contrib.auth.backends.ModelBackend',  # ← Стандартный
]


# 🔹 Дополнительные настройки из .env (на будущее)
# === Email ===
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@constanta.local')

# === Производительность ===
# TODO: Добавить кэширование (Redis / Memcached)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# === Сессии ===
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=1209600)  # 2 недели
SESSION_SAVE_EVERY_REQUEST = env.bool('SESSION_SAVE_EVERY_REQUEST', default=False)

# === Сообщения ===
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# === Лимиты ===
MAX_FRIENDS_PER_USER = env.int('MAX_FRIENDS_PER_USER', default=500)
MAX_GROUPS_PER_USER = env.int('MAX_GROUPS_PER_USER', default=50)
MAX_MESSAGE_LENGTH = env.int('MAX_MESSAGE_LENGTH', default=2000)