# Generated by Django 6.0.3 on 2026-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_ban_reason_user_banned_at_user_banned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, default='Нарушение правил'),
        ),
    ]
