# Generated by Django 6.0.3 on 2026-03-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_user_ban_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог админа', 'verbose_name_plural': 'Логи админа'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Дружба', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники групп'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'Нет'), ('image', 'Изображение'), ('file', 'Файл'), ('voice', 'Голосовое')], default='none', max_length=20),
        ),
    ]
