# Generated by Django 6.0.3 on 2026-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_adminlog_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['attachment_hash'], name='messages_attachm_8585a8_idx'),
        ),
    ]
