# Generated by Django 6.0.3 on 2026-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_attachment_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
