# Generated by Django 6.0.4 on 2026-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
