# Generated by Django 6.0.4 on 2026-05-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
    ]
