# Generated by Django 6.0.4 on 2026-05-27 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-Адрес')),
                ('reason', models.TextField(blank=True, verbose_name='Причина бана')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бана')),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_ips', to=settings.AUTH_USER_MODEL, verbose_name='Забанил админ')),
            ],
            options={
                'verbose_name': 'Заблокированный IP',
                'verbose_name_plural': 'Заблокированные IP',
                'ordering': ['-banned_at'],
            },
        ),
    ]
